version: "3.8"

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: bookstore_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bookstore-network

  # Node.js App Service
  app:
    build: .
    container_name: bookstore_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/bookstore
      JWT_SECRET: your_super_secret_jwt_key_change_this_in_production
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - bookstore-network

  # Mongo Express (Database UI)
  mongo-express:
    image: mongo-express:latest
    container_name: bookstore_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - bookstore-network

volumes:
  mongo-data:

networks:
  bookstore-network:
    driver: bridge
